### ISSUE TITLE
Função basepath sempre retorna sandbox independente de PJBANK_DEVELOPER_MODE ser true ou false

### ISSUE THREAD

**Issue by gitFabio** [pjbank/pjbank-api-client#3]
A funçao *basepath* sempre retorna sandbox porque ao não dar erro na função **Boolean** o resultado sempre vai ser verdadeiro

Boolean('true') === true -  verdadeiro (função retorna sucesso)
Boolean('false') === true -  verdadeiro (função retorna sucesso)

Acho que a solução seria comparar string mesmo:

```
basepath: () => {
        if (process.env.PJBANK_DEVELOPER_MODE === 'true') {
            return Sandbox;
        } else {
            return Production;
        }
    }
```

Como que eu faço pra submeter minha possível solução?

**Comment by msfidelis** [comment]
Fala @gitFabio, pode abrir um pull request normalmente e vincular ele na sua issue! 
Obrigado pela contribuição! 👍

**Comment by msfidelis** [comment]
https://github.com/pjbank/pjbank-api-client/pull/4
